function pvwattshourly = import_pvwatts_hourly(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PVWATTSHOURLY = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PVWATTSHOURLY = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  pvwattshourly = import_pvwatts_hourly("data\pvwatts_hourly.csv", [19, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Dec-2020 18:13:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [19, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Month", "Day", "Hour", "BeamIrradianceWm2", "DiffuseIrradianceWm2", "AmbientTemperatureC", "WindSpeedms", "PlaneofArrayIrradianceWm2", "CellTemperatureC", "DCArrayOutputW", "ACSystemOutputW"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
pvwattshourly = readtable(filename, opts);

end