function mustBeArrayFromClass(objs, class_name)
%MUSTBEARRAYFROMCLASS Validate that value is a cell array of objects
%   `mustBeArrayFromClass(objs, class_name)` issues an error if `objs` is
%   not a cell array of objects that descend from (i.e., are a class or a
%   subclass of) `class_name`

assert( iscell(objs), ...
    'MATLAB:mustBeArrayFromClass:NOT_CELL', ...
    'objs must be a cell array');

assert( all( cellfun( ...
        @(obj)ismember(class_name, [class(obj); superclasses(obj)]), ...
        objs)), ...
    'MATLAB:mustBeArrayFromClass:NOT_DESCENDED_FROM', ...
    'All objs must be descended from class_name' )

end

