function plot(obj,plot_title)
%PLOT Plot the system
if ~exist('plot_title','var')
    plot_title = obj.NAME;
end

% Construct table of data to plot
gens_P_generated = cellfun(@(x)(x.P_generated),obj.gens, ...
    'UniformOutput',false);
batts_charge = cellfun(@(x)(x.charge(:)),obj.batts, ...
    'UniformOutput',false);
plot_table = timetable(obj.DATETIME, ...
    obj.demand(:), ...
    gens_P_generated{:}, ...
    obj.curtailed(:), ...
    batts_charge{:});
% Convert table from kW to MW
plot_table = varfun(@(x)(x/1E3), plot_table);

% Give names to table columns
gens_name = cellfun(@(x)(x.NAME),obj.gens, ...
    'UniformOutput',false);
batts_name = cellfun(@(x)(x.NAME),obj.batts, ...
    'UniformOutput',false);
plot_table.Properties.VariableNames = {...
    'demand', ...
    gens_name{:}, ...
    'curtailed', ...
    batts_name{:}};

% Plot table in stacked plot
figure('windowstyle','docked')
hsp = stackedplot(plot_table, ...
    'DisplayVariables', {...
        {'demand',gens_name{:}}, ...
        'curtailed', ...
        {batts_name{:}} }, ...
    'DisplayLabels', {...
        'Power (MW)', ...
        'Curtailments (MW)', ...
        'Stored Energy (MWh)'}, ...
    'Title', [obj.NAME ': ' plot_title]);




end

