function plot(obj,plot_title)
%PLOT Plot the system
if ~exist('plot_title','var')
    plot_title = obj.NAME;
end

% Construct table of data to plot
plot_table = timetable(obj.DATETIME, ...
    obj.demand(:), ...
    obj.supply(:), ...
    obj.curtailed(:), ...
    obj.batts{1}.charge(:), ...
    obj.batts{2}.charge(:) );

% Give names to table columns
plot_table.Properties.VariableNames = {...
    'demand', ...
    'supply', ...
    'curtailed', ...
    'LIB', ...
    'flow'};

% Plot table in stacked plot
figure('windowstyle','docked')
hsp = stackedplot(plot_table, ...
    'DisplayVariables', {...
        {'demand','supply'}, ...
        'curtailed', ...
        {'LIB','flow'} }, ...
    'DisplayLabels', {...
        'Power (kW)', ...
        'Curtailments (kW)', ...
        'Stored Energy (kWh)'}, ...
    'Title', [obj.NAME ': ' plot_title]);




end

